version: "3.9"

services:

  voting:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 2
  
  redis:
    image: redis:3.2
    networks:
      - frontend
    deploy:
      replicas: 1
  
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis
    deploy:
      mode: replicated
      replicas: 1
          
  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
  
  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - 81:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1

networks:
  frontend:
  backend:

volumes:
  db-postgres: